---
title: "Extra Plots"
author: "Ethan Shen"
date: "6/4/2020"
output: 
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning=F,
                      message=F)
library(dplyr)
library(ggplot2)
library(sf)
```

```{r}
nc112 = st_read('data/nc_districts112.shp', quiet=TRUE, stringsAsFactors=TRUE)
nc114 = st_read('data/nc_districts114.shp', quiet=TRUE, stringsAsFactors=TRUE)
nc=st_read("nc_counties.gpkg", quiet=TRUE)
```


# 3C.1

```{r}
ggplot() + 
  geom_sf(data=nc112, aes(fill=DISTRICT)) + 
  geom_sf(data=nc, fill=NA) + 
  labs(title = "NC112") + 
  guides(fill = guide_legend(ncol=2))

ggplot() + 
  geom_sf(data=nc114, aes(fill=DISTRICT)) + 
  geom_sf(data=nc, fill=NA) + 
  labs(title = "NC114") + 
  guides(fill = guide_legend(ncol=2))
```


```{r}
nc112_intersection = st_intersection(nc, nc112  %>%
                                       st_transform(st_crs(nc))%>% filter(DISTRICT==11))

nc114_intersection = st_intersection(nc, nc114  %>%
                                       st_transform(st_crs(nc))%>% filter(DISTRICT==11))
ggplot()  + 
  geom_sf(data=nc112_intersection,
          aes(fill=COUNTY)) +
  geom_sf(data = nc112 %>% filter(DISTRICT==11), fill=NA)
ggplot() + 
  geom_sf(data=nc114_intersection,
          aes(fill=COUNTY))+
  geom_sf(data = nc114 %>% filter(DISTRICT==11) , fill=NA)
```

```{r}
st_sym_difference(nc114 %>% filter(DISTRICT==11),
                  nc112 %>% filter(DISTRICT==11)) %>%
  ggplot() + 
  geom_sf(col="NA", fill="lightblue") + 
  geom_sf(data=nc, fill=NA)

```

```{r message=FALSE, warning=FALSE}
ggplot() + 
  geom_sf(data=nc112 %>% filter(DISTRICT==11), fill="blue", alpha=0.4) + 
  geom_sf(data=nc114 %>% filter(DISTRICT==11), fill="blue", alpha=0.4) + 
  geom_sf(data=nc, fill="NA")
```

